### ISSUE TITLE
👍感谢大佬，能不能抽空做个EPG！

### ISSUE THREAD

**Issue by rushidea** [lesca/jiangsu-iptv#2]
果然换了联通，换台秒切😄

**Comment by lesca** [comment]
没有计划。如有能力，欢迎PR

**Comment by xuexie0403** [comment]
终于找到一位大佬抓取江苏联通的直播源了，直播源很久了，江苏各个台现在好像都是1080了，大佬可以从新抓取一次吗？还是要感谢大佬。这个源终于秒开了。盐城也可以使用

**Comment by lesca** [comment]
@xuexie0403 运行 `get_js_unicom_iptv.py` 获取最新源。而且现在的源也没问题

**Comment by xuexie0403** [comment]
不会啊，这个怎么运行啊，或者哪里有教程也行
